# Generated by Django 4.2 on 2023-06-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.TextField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_finished_intro', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(max_length=8)),
                ('word', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='word_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_source', to='api.word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='word_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_target', to='api.word'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('has_finished_generation', models.BooleanField(default=False)),
                ('language', models.TextField(max_length=80)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_source', models.TextField(max_length=80)),
                ('example_target', models.TextField(max_length=80)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.translation')),
            ],
        ),
    ]
