# Generated by Django 4.2 on 2023-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='has_finished_intro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
