# Generated by Django 4.2 on 2023-06-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customusermodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(max_length=100)),
                ('code', models.TextField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='mother_tongue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language'),
        ),
    ]
