# Generated by Django 4.2 on 2023-06-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_active_customusermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('language', 'code')},
        ),
    ]
