# Generated by Django 4.2 on 2023-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_language_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='lemmas',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
