# Generated by Django 4.2 on 2023-06-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_text_lemmas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='example',
            unique_together={('translation', 'example_source', 'example_target')},
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('word_source', 'word_target')},
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('language', 'word')},
        ),
    ]
