# Generated by Django 4.2 on 2023-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_example_sourceprefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='credit',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
