# Generated by Django 4.2 on 2023-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customusermodel_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='provider',
            field=models.CharField(choices=[('microsoft', 'Microsoft'), ('yandex', 'Yandex')], default='microsoft', max_length=20),
        ),
    ]
