# Generated by Django 4.2 on 2023-07-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_translation_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('word_source', 'word_target', 'provider')},
        ),
    ]
