# Generated by Django 4.2 on 2024-02-15 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_translation_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='sourcePrefix',
            new_name='source_prefix',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='sourceSuffix',
            new_name='source_suffix',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='sourceTerm',
            new_name='source_term',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='targetPrefix',
            new_name='target_prefix',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='targetSuffix',
            new_name='target_suffix',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='targetTerm',
            new_name='target_term',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='provider',
            field=models.CharField(choices=[('microsoft', 'Microsoft'), ('yandex', 'Yandex'), ('chatgpt', 'ChatGPT')], default='microsoft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('name', 'code')},
        ),
    ]
