# Generated by Django 4.2 on 2024-02-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_sourceprefix_example_source_prefix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='userId',
            new_name='user_id',
        ),
    ]
